version: "3.8"
services:

  mysql_db:
    container_name: mysql_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - new

  nest_app:
    container_name: nest_app
    image: nest_server_template
    build: ./BookBackend
    ports:
      - "3000:3000"
    depends_on: 
      - mysql_db
    networks:
      - new

  react_app:
    container_name: react_app
    image: react_app_template
    build: ./BookFrontend
    ports:
      - "3008:3008"
    networks:
      - new
  networks:
  new:
