version: "3.8"
services:
  react_app:
    container_name: react_app
    image: react_app_template
    build: ./BookBackend
    ports:
      - "3000:3000"

  node_server:
    container_name: node_server
    image: node_server_template
    build: ./BookFrontend
    ports:
      - "3008:3008"
    depends_on: mysql

  mysql_db:
    container_name: mysql_db
    image: mysql
    build: ./BookFrontend
    ports:
      - "3307:3307"
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root

